### PR TITLE
Hotfix, make team_class field optional

### PR DESCRIPTION
**Pull request by Antoni-Czaplicki**

### CODE REVIEW

**Comment by kuba2k2** [comment]
Wow, but why

Even the ID?

**Comment by Antoni-Czaplicki** [comment]
> Wow, but why
> 
> Even the ID?

That's Vulcan, I'd rather do one big PR than a few smaller ones. Last time I got error about class field.

```
Logger: homeassistant.components.sensor
Source: custom_components/vulcan/fetch_data.py:214
Integration: Sensor (documentation, issues)
First occurred: 7:06:42 (1 occurrences)
Last logged: 7:06:42

Error while setting up vulcan platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/vulcan/sensor.py", line 97, in async_setup_entry
    "exam": await get_next_exam(client),
  File "/config/custom_components/vulcan/fetch_data.py", line 214, in get_next_exam
    async for exam in await client.data.get_exams():
  File "/usr/local/lib/python3.9/site-packages/vulcan/data/_exam.py", line 61, in get
    yield Exam.load(exam)
  File "/usr/local/lib/python3.9/site-packages/vulcan/model/_serializable.py", line 49, in load
    return to_model(cls, data)
  File "/usr/local/lib/python3.9/site-packages/related/functions.py", line 104, in to_model
    value = cls(**value)
TypeError: __init__() missing 1 required positional argument: 'team_class'
```

**Comment by kuba2k2** [comment]
Well, still, I'm not sure if making everything optional is a good solution. That would be like using stupid non-typed non-null-safe JavaScript, and we don't want this here.

I suggest marking some of these as required, i.e. ID, Key, Date/Time, Type, Topic, and maybe some other. It's ok for the team/class which may be somehow unspecified (Vulcan magic, true) but I'm pretty sure there can be no exam without the fields I mentioned before.

**Comment by Antoni-Czaplicki** [comment]
> Well, still, I'm not sure if making everything optional is a good solution. That would be like using stupid non-typed non-null-safe JavaScript, and we don't want this here.
> 
> I suggest marking some of these as required, i.e. ID, Key, Date/Time, Type, Topic, and maybe some other. It's ok for the team/class which may be somehow unspecified (Vulcan magic, true) but I'm pretty sure there can be no exam without the fields I mentioned before.

Ok, you're right

**Review by kuba2k2 — APPROVED** [review]

**Review by kapi2289 — APPROVED** [review]

**Pull request merged**
